### ISSUE TITLE
Incompatibility with Screenshot to Clipboard (Fabric) causes a crash

### ISSUE THREAD

**Issue by amnotbananaama** [modmuss50/OptiFabric#112]
(I want to preface this issue by saying thank you for maintaining this resource. I am not very knowledgeable about Java or Fabric, so I hope I described this issue in a helpful manner.) 

The remapping of Fabric done by OptiFabric  prevents the mod [Screenshot to Clipboard (Fabric)](https://www.curseforge.com/minecraft/mc-mods/screenshot-to-clipboard-fabric) from working. According to the developer, the mod "tries to inject into a lambda method in class_318 [net/minecraft/client/util/ScreenshotUtils], that presumably doesn't exist or hasn't been mapped properly when it's patched by OptiFabric." This actually caused me to crash when I pressed the F2 key. 

**Crash Log**
https://paste.ee/p/Ya5Vx

**Chat Log**
https://paste.ee/p/WzbfR

**Fabric Version**
Fabric API 0.4.2+build.246-1.14
Fabric Loader 0.7.3+build.176

**Mod List**
Custom Selection Box Fabric 3.2.0
Horse Stats Vanilla 1.0.1
Litematica 0.0.0-dev.20191222.014040
MaLiLib 0.10.0-dev.20
MiniHUD 0.19.0-dev.20191007.003640
Mod Menu 1.7.15.1.14.4+build.127
Optifabric 0.7.1
Screenshot to Clipboard 1.0.3
Shulker Box Tootip 1.3.1+1.14.4
Tooltip Autowrap 1.0.0

**Comment by modmuss50** [comment]
humm, thanks I guess I may need to improve the lamabad fixes I do to optifine before applying it.

**Comment by modmuss50** [comment]
Closing, the 1.14.4 version is no longer supported.

**Comment by amnotbananaama** [comment]
Thank you for updating to 1.15.2 so quickly! I can still reproduce this issue (same exact crash error) with the 1.15.2 version of OptiFabric. Should I open a new issue?

**Crash Log**
https://pastebin.com/rGT2qiek

**Chat Log**
https://pastebin.com/uWsE901K

**Fabric Version**
Fabric API 0.4.32+build.292-1.15
Fabric Loader 0.7.8+build.184

**Mod List**
preview_OptiFine_1.15.2_HD_U_G1_pre1
optifabric-1.0.0-beta3
ScreenshotToClipboardFabric-1.0.3

**Comment by comp500** [comment]
Hey @modmuss50, this issue still seems to occur!

It seems to be because I have 2 mixins to a lambda function (one of which can be moved, the other I don't think I can move it outside the lambda function), and when Optifabric patches that function it renames it to `lambda$saveScreenshotRaw$2` from `method_1661` (intermediary), so my mixins fail to apply.

I think the solution (without me moving my injection points) is either for Optifabric to get the correct method name, or for the name to be predictable (maybe `lambda$method_1662$2` should be used instead... not sure why it uses the yarn name of `saveScreenshotRaw` here) so that I can handle this with a mixin config plugin or optional injections.

If you're going to test this, do note that my second mixin runs on INVOKE of Consumer#accept, which has another call in the Optifine version of the code, which may be broken (it only uses that on macOS though).

Related issue: https://github.com/comp500/ScreenshotToClipboard/issues/6

Edit: This is with Optifabric 1.0.0-beta8, Optifine 1.15.2 HD U G1 pre13, Screenshot to Clipboard 1.0.4

**Comment by Chocohead** [comment]
Worth mentioning perhaps that `saveScreenshotInner` is the Yarn name. As Optifine recompiles with MCP names all the lambdas are named from the containing MCP named method, hence the loss of Intermediary names. Mapping them back is [largely possible](https://github.com/Chocohead/Fabric-Loom/blob/leaf/src/main/java/net/fabricmc/loom/providers/openfine/MethodChanges.java#L77-L114) (except where Optifine changes the number in a method to the point where you eventually have to resort to [hard coding](https://github.com/Chocohead/Fabric-Loom/blob/leaf/src/main/java/net/fabricmc/loom/providers/openfine/MethodChanges.java#L116-L189)), but it may prove simpler to hard code specific examples where this is a problem.

**Comment by comp500** [comment]
With some help from Chocohead, I've managed to solve this bug! (see https://github.com/comp500/ScreenshotToClipboard/commit/67c306df2174db58f472a0c5834fde5fd45dbc86)
