### ISSUE TITLE
Crash on 1.14.2

### ISSUE THREAD

**Issue by severusDude** [modmuss50/OptiFabric#114]
I got a crash when playing on 1.14.2.the problem happened after Mojang splashscreen which say **Failed to load optfine, check the log for more info       org/spongepowered/asm/lib/ClassWriter**

**Fabric version:**
fabric-loader-0.7.6+build.180-1.14.2
fabric-api-0.3.0+build.185

**Mods:**
optifabric-0.2.0
ModMenu-1.6.1-90
minihud-fabric-1.14.2-0.19.0-dev.20190624.221851
malilib-fabric-1.14.2-0.10.0-dev.20
litematica-fabric-1.14.2-0.0.0-dev.20190624.221035

**Optifine:**
preview_OptiFine_1.14.2_HD_U_F1_pre15

here is my log

[latest.log](https://github.com/modmuss50/OptiFabric/files/4116571/latest.log)

**Comment by amnotbananaama** [comment]
Most likely OptiFabric isn't detecting the Optifine jar because it is a preview version. Can I ask why you are still playing on 1.14.2? 1.14.3 and 1.14.4 have full versions of Optifine, and fixed numerous bugs.

If the "god armor" enchanting in 1.14.2 is what is holding you back from updating, I'd recommend checking out the Protection Renewal mod, which works in 1.14.3+
https://www.curseforge.com/minecraft/mc-mods/protection-renewal

Edit: See Issue https://github.com/modmuss50/OptiFabric/issues/99, you need to update OptiFabric to version 0.7.0

**Comment by modmuss50** [comment]
Closing, the 1.14.4 version is no longer supported.
