### ISSUE TITLE
crash after launching

### ISSUE THREAD

**Issue by DanShu15** [modmuss50/OptiFabric#202]
I probably screwed something up. I've added preview_OptiFine_1.15.2_HD_U_G1_pre16 and OptiFabric to my All of Fabric 2 install that I'm swapping mods in and out of.
Before adding them I launched the pack and it loaded fine. 
After adding them when I launch I'm returned to the Minecraft Launcher with a screen stating
Error
Game crashed
An unexprected issue occurred and the game has crashed. We're sorry for the inconvenience.
crash log
https://pastebin.com/wP6FH035

**Comment by JoJo9127** [comment]
so i managed to find a fix for it when it comes to launching but basically i missed a step and i didn't put optifine installer jar within the mod folder so make sure you have opti-fabric and optifine together in the mod folder and should just work fine im just working through my mod list since im getting a diffrent error now but hopefully this fixes your issues with it.

**Comment by 0xfeeddeadbeef** [comment]
Judging from the crash log, the cause of crash is Lithium, not OptiFabric.

**Comment by modmuss50** [comment]
lithium wont work with optifabric. please remove optifabric
