### ISSUE TITLE
Failed to load optifine, check the log for more info.

### ISSUE THREAD

**Issue by msglm** [modmuss50/OptiFabric#44]
Error: net.fabricmc.loader.launch.common.FabricLauncher.getLoadTimeDependenceis()Ljava/util/Collection;

Log File:
[latest.log](https://github.com/modmuss50/OptiFabric/files/3413707/latest.log)

Mods:
fabric-api-0.3.0+build.198 (https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/2742310)
litematica-fabric-1.14.3-0.0.0-dev.20190630.024955 (https://www.curseforge.com/minecraft/mc-mods/litematica/files/2736014)
malilib-fabric-1.14.3-0.10.0-dev.20 (https://www.curseforge.com/minecraft/mc-mods/malilib/files/2736002)
optifabric-0.4.2 (https://www.curseforge.com/minecraft/mc-mods/optifabric/files/2744375)
OptiFine_1.14.3_HD_U_F1 (https://optifine.net/downloadx?f=OptiFine_1.14.3_HD_U_F1.jar&x=678f9b1306978065601083bb4c491239)

**Comment by modmuss50** [comment]
try updating fabric loader

**Comment by msglm** [comment]
Thank you, it worked

**Comment by nogutsnoglory69** [comment]
I've got the same issue with the 1.14.4 version.  My fabric loader is the most recent one.
I'm using:
fabric api 0.3.0 build 200
malilib 1.14.4 0.10.0
minihud 1.14.4 [0.19.0]
optifabric 0.4.3
optifine 1.14.4 pre1
tweakaroo 1.14.4 0.9.8.

here's my log: 
[latest.log](https://github.com/modmuss50/OptiFabric/files/3426973/latest.log)

I would really love to know what exactly i can do to fix this. All versions before the 1.14.4 one worked flawlessly for me. 


Edit: fixed with the full release of optifine for 1.14.4.
