### ISSUE TITLE
Optifabric for 1.14.4

### ISSUE THREAD

**Issue by thatguyontv** [modmuss50/OptiFabric#63]
Hi, 

I tried installing Optifabric and Optifine for MC/Fabric 1.14.4 and it doesn't work. I know the installation guide says to use 1.14.3 but I wanted to use the latest version. I downloaded Optifine for 1.14.4 and the game crashed, then Optifine for 1.14.3 and it said I needed game version 1.14.3. Is there a way to fix this or must the mod itself be updated to 1.14.4?
![Capture](https://user-images.githubusercontent.com/51293744/63636899-fe36fa80-c675-11e9-98f7-852a79180aea.PNG)

**Comment by calloatti** [comment]
The tutorial uses 1.14.3 because 1.14.4 did not exist when I wrote it.

The tutorial also says:

> For the rest of the tutorial we will use a MC/Fabric 1.14.3 instance as an example. You may need newer file versions for newer MC versions.

You should download optifine and optifabric for 1.14.4 and it should work. If the game crashes, try with no mods, and add mods until it crashes, that way you will know what mod is causing the crash.

Also, if it crashes, without a log is hard to know what is going on.

You can also try the the Fabric Discord for support: https://discord.gg/v6v4pMv

**Comment by thatguyontv** [comment]
I tried this again with your suggestion, no other mods and latest versions, but I still got this error message:
![Capture](https://user-images.githubusercontent.com/51293744/63643189-6237de00-c6cb-11e9-953b-160b6210c910.PNG)

**Comment by thatguyontv** [comment]
Updated Optifine to the latest version and found some conflicting mods. Thanks!
