### ISSUE TITLE
Optifine Pre 5 and 6 water issue

### ISSUE THREAD

**Issue by MetallicAsylum** [modmuss50/OptiFabric#7]
Hi, I have an issue with OptiFabric compatability and Optifine Pre 5&6. Everything works fine (exept shaders but whatever) but the water. Each water is divided into a seperate block, making the water basically impossible to see through. (See Screenshot) and I was wondering what I could do, as the previous versions of optifine are gone, and I can't download them.

Thanks!
![2019-05-27_14 03 53](https://user-images.githubusercontent.com/51097757/58439317-51ee7380-8088-11e9-8f32-2da938ed6f13.png)
![2019-05-27_14 03 57](https://user-images.githubusercontent.com/51097757/58439325-53b83700-8088-11e9-9773-fcb4263b99aa.png)

**Comment by modmuss50** [comment]
Humm, what version of fabric api do you have?

I think the water is caused by the fluid rendering api that was added, I need to look into this some more.

As for shaders the newest versions of fabric api from: [CurseForge](https://minecraft.curseforge.com/projects/fabric/files) should fix it. (the 1.14.2 versions should work on 1.14).

Ill look into the water issue some more and see if I can find a solution to it.

**Comment by modmuss50** [comment]
Ok, so ive done a bit of testing, shaders are still broken.

The water issue seems to have gone with the latest version of the api.

**Comment by MetallicAsylum** [comment]
Thanks for all the help!

**Comment by MamiyaOtaru** [comment]
water and shaders broken with api 175.  Downgrading api to 157 fixes both for me in 1.14.2

**Comment by MythikAngel** [comment]
The newest release of OptiFabric (0.2.0) seems to have fix the water issue with using the newest Fabric API (175).

**Comment by modmuss50** [comment]
This is an odd one, I tested it on the latest version and it seemed alright but others have reported issues.

**Comment by modmuss50** [comment]
This issue will not be fixed, sorry about that.

More info: https://github.com/modmuss50/OptiFabric/blob/master/README.md
